pipeline {
    agent any

    stages {
        stage('Clone project from github') {
            steps {
                dir('/root') {
                    git(url: 'https://github.com/ivangavrilov-viii/devops.git', branch: 'master')
                }
            }
        }

        stage('Start terraform') {
            steps {
                dir('devops/Exam') {
                    sh '''
                        terraform init
                        terraform validate
                        terraform apply
                    '''
                }
            }
        }
    }
}