---
services:
  build_app:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - app_data:/app/target/

  prod_service:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - app_data:/var/lib/tomcat9/webapps/
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=app_db
      - DB_USER=root
      - DB_PASSWORD=root_password
    depends_on:
      - build_app
      - db

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  app_data:
  db_volume:
...