---
version: '3.8'

services:
  build_app:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - app_data:/app/target

  prod_service:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - app_data:/app/target
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=root
      - DB_PASSWORD=root_password
    depends_on:
      - build_app
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  app_data:
  db_volume:
...