---
version: '3.8'

services:
  build_app:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - app_data:/app/target

  prod_service:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - app_data:/app/target
    depends_on:
      - build_app
      - db

#  db:
#    image: mysql:8.0
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword
#      - MYSQL_DATABASE=db
#    ports:
#      - '3306:3306'
#    volumes:
#      - db_volume:/var/lib/mysql

volumes:
  app_data:
  db_volume:
...