---
version: '3.8'

services:
  build_app:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - app_data:/app/target

  prod_service:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - app_data:/app/target
    environment:
      - DB_HOST=db
      - DB_PORT=8514
      - DB_NAME=dd
      - DB_USER=acp4pogynvaeidfj
      - DB_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    depends_on:
      - build_app
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    ports:
      - "8514:8514"
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  app_data:
  db_volume:
...