---
version: '3.8'
services:

  production:
    build:
      context: ./production
      dockerfile: production.Dockerfile
    volumes:
      - build_volume:/var/lib/tomcat9/webapps/
    ports:
      - '8080:8080'
    environment:
      - MYSQL_USER=root
      - MYSQL_PORT=5432
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_HOST=158.160.79.92
      - MYSQL_DATABASE=db
    depends_on:
      - db
      - builder

  builder:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - build_volume:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=db
    ports:
      - '3306:3306'
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  build_volume:
  db_volume:
...