---
services:
  build_app:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - app_data:/app/target/
      - root_data:/ROOT/

  prod_service:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - app_data:/var/lib/tomcat9/webapps/
      - root_data:/ROOT/
    depends_on:
      - build_app
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_PASSWORD: root_password
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  app_data:
  db_volume:
  root_data:
...