---
version: '3.8'
services:
  builder:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - build_volume:/app/target/

  production:
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - build_volume:/app
    ports:
      - '8080:8080'
    environment:
      - MYSQL_USER=root
      - MYSQL_PORT=5432
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_HOST=158.160.79.92
      - MYSQL_DATABASE=db
    depends_on:
      - builder
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=db
    ports:
      - '3306:3306'
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  build_volume:
  db_volume:
...