pipeline {
    agent {
        docker {
            image 'gavril23/base_image:latest'
        }
    }

    stages {
        stage('Clone project from github') {
            steps {
                git(url: 'https://github.com/ivangavrilov-viii/boxfuse-app.git', branch: 'master')
            }
        }

        stage('Build WAR') {
            steps {
                dir('boxfuse-app') {
                    sh 'mvn package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('boxfuse-app') {
                    sh 'cp target/hello-1.0.war .'
                    sh 'docker build -t gavril23/hw_11 . '
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'docker login -u $DOCKER_USER -p $DOCKER_PASSWORD'
                        sh 'docker push gavril23/hw_11'
                    }
                }
            }
        }

        stage('Run docker on build_server') {
            steps {
                sh 'ssh-keyscan -H build_server >> ~/.ssh/known_hosts'
                sh '''ssh root@build_server << EOF
                    docker pull gavril23/hw_11
                    docker run -d -p 8080:8080 gavril23/hw_11
                    EOF
                '''
            }
        }
    }

    triggers {
        pollSCM('*/1 H * * *')
    }
}